-- seu-script-dados.sql - dados de teste
INSERT INTO EQUIPE_MANUTENCAO (NOME, ESPECIALIDADE) VALUES ('Equipe Norte','Roçada');
INSERT INTO EQUIPE_MANUTENCAO (NOME, ESPECIALIDADE) VALUES ('Equipe Sul','Pulverização');
INSERT INTO TRECHO_RODOVIA (KM, ALTURA_VEGETACAO, TIPO_TERRENO, EQUIPE_ID) VALUES (10,120,'umido',1);
INSERT INTO TRECHO_RODOVIA (KM, ALTURA_VEGETACAO, TIPO_TERRENO, EQUIPE_ID) VALUES (25,80,'seco',2);
INSERT INTO TRECHO_RODOVIA (KM, ALTURA_VEGETACAO, TIPO_TERRENO) VALUES (40,20,'seco');
INSERT INTO INTERVENCAO_OPERACIONAL (KM_TRECHO,TIPO,RESPONSAVEL) VALUES (10,'ROÇADA_MECANIZADA','Equipe Norte');
COMMIT;
