-- seu-script-dados.sql - dados de teste
INSERT INTO EQUIPE_MANUTENCAO (NOME, ESPECIALIDADE, DIRECAO) VALUES ('Equipe Norte','Rocada','NORTE');
INSERT INTO EQUIPE_MANUTENCAO (NOME, ESPECIALIDADE, DIRECAO) VALUES ('Equipe Sul','Pulverizacao','SUL');
INSERT INTO TRECHO_RODOVIA (KM, ALTURA_VEGETACAO, TIPO_TERRENO, EQUIPE_ID) SELECT 10,120,'umido',ID FROM EQUIPE_MANUTENCAO WHERE NOME='Equipe Norte';
INSERT INTO TRECHO_RODOVIA (KM, ALTURA_VEGETACAO, TIPO_TERRENO, EQUIPE_ID) SELECT 25,80,'seco',ID FROM EQUIPE_MANUTENCAO WHERE NOME='Equipe Sul';
INSERT INTO TRECHO_RODOVIA (KM, ALTURA_VEGETACAO, TIPO_TERRENO) VALUES (40,20,'seco');
INSERT INTO INTERVENCAO_OPERACIONAL (KM_TRECHO,TIPO,RESPONSAVEL) VALUES (10,'ROCADA_MECANIZADA','Equipe Norte');
COMMIT;
